env:
  CODECLIMATE_REPO_TOKEN: 2c69088994c72bf118aa50db292210e118f03e27fda7d93a2d72153a98dc536a
language: node_js
node_js:
  - "7.8.0"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter before-build --exit-code $TRAVIS_TEST_RESULT; fi
  - "cd server/"
  - "npm install"
script:
  - npm test
  - npm run coverage
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
after_success:
  - npm run coveralls
