env:
  global:
    - NODE_ENV=test
    - PGPORT=5432
    - PGHOST=localhost
  CODECLIMATE_REPO_TOKEN: 5ba0fafe4174fbd93d8e91e7decf4f8c3b5eb4ade63f5d136d9733481324eac3
language: node_js
node_js:
  - "7.8.0"
services:
  - postgresql
before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
  - sudo /etc/init.d/postgresql start
before_script:
  - psql -c "CREATE DATABASE 'event-manager-test';" -U postgres
  - psql -c "CREATE USER robocopkaka WITH PASSWORD 'annabeth';" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - "npm install"
script:
  - npm test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build
after_success:
  - npm run coveralls
